### ISSUE TITLE
你好我想知道这个是在哪里写

### ISSUE THREAD

**Issue by sjzjams** [OrangeXC/n2ex#124]
Node proxy solve CORS

**Comment by OrangeXC** [comment]
https://github.com/OrangeXC/n2ex/blob/master/nuxt.config.js#L29

baseURL 指向了一个 node proxy 服务，proxy 负责请求转发，从而解决客户端跨域问题

**Comment by sjzjams** [comment]
@OrangeXC 谢谢，我通过你说的方式在now.sh上面部署了自己的服务
