### ISSUE TITLE
怎么部署到服务器上，我在服务器上部署不了

### ISSUE THREAD

**Issue by Aric-sky** [OrangeXC/n2ex#134]
服务器端npm run build,  然后npm start，ip+端口号，无法访问

**Comment by Aric-sky** [comment]
内网的ip不行吗？

**Comment by Aric-sky** [comment]
npm start命令需要切换到对应的入口文件下执行吗，client 和 server 两个入口文件

**Comment by OrangeXC** [comment]
@Aric-sky  
不需要
