### ISSUE TITLE
如何配置跨域请求

### ISSUE THREAD

**Issue by jsgr** [OrangeXC/n2ex#14]
请问下，我在代码里并未找到配置转发跨域请求的代码。而且用 https://proxy-uuptfgaypk.now.sh/topics/latest.json  就可以直接访问，请问是在哪里做转发的。博客了写了，可是在项目里没有找到对应的代码。我用浏览器 打开 https://proxy-uuptfgaypk.now.sh/topics/latest.json 也可以请求到数据，请问这是怎么配置的？

**Comment by OrangeXC** [comment]
是一个 express 的 node 项目，你自己本地新建一个 express 项目然后把代码粘贴进去跑就行了

**Comment by jsgr** [comment]
好的，谢谢
