### ISSUE TITLE
本地npm run dev报错

### ISSUE THREAD

**Issue by sunlianlong** [OrangeXC/n2ex#17]
报错信息：
![image](https://user-images.githubusercontent.com/22101668/29501234-a62199f8-8659-11e7-940e-6c453d1cf0e0.png)
 __WEBPACK_IMPORTED_MODULE_2_nuxt___default.a is not a constructor

是在控制台报的错误，信息量太少，我这里无法提供更多的信息，另外我在寻找NUXT并发请求的方法，看你的项目中有，按你的代码执行后也报和上面类似的错误：
__WEBPACK_IMPORTED_MODULE_0__plugins_axios__.a.all is not a function

如果有时间的话希望能够帮忙看看是否是我本地的问题（win7 64）

**Comment by OrangeXC** [comment]
首先说下你遇到的问题，axios.all 方法在 @nuxtjs/axios 官方库是没有封装的，如果想并发请求可以直接使用 Promise.all 方法，不清楚使用的话可以去 google 或 百度

**Comment by sunlianlong** [comment]
麻烦把这个issues关闭掉吧，莫名其妙的又好使了，不知道什么原因，就是在npm install 后执行 npm run dev报的错，再研究吧。

**Comment by OrangeXC** [comment]
@sunlianlong 小问题，尝试升级下 npm，或者采用 yarn，希望找到问题后分享下
