### ISSUE TITLE
想请教一下，微信分享怎么集成到nuxt

### ISSUE THREAD

**Issue by hurely** [OrangeXC/n2ex#21]
你好大神，nuxt下怎么用微信分享的，现在用weixin-js-sdk但是一只保window is not defined，不知道是怎么回事

**Comment by OrangeXC** [comment]
可以看下这个 issue： https://github.com/nuxt/nuxt.js/issues/30

关于 nuxt 用法的问题在 nuxt 项目下基本都可以找得到
