### ISSUE TITLE
这个项目seo有问题

### ISSUE THREAD

**Issue by lichenabson** [OrangeXC/n2ex#223]
这个项目页面跳转 都是通过js去跳转的, 爬虫无法爬取. 所以你的站点内的文章都无法通过搜索引擎检索到
![image](https://user-images.githubusercontent.com/20200267/54736526-75a7c000-4be6-11e9-915d-329305eb3831.png)
![image](https://user-images.githubusercontent.com/20200267/54736623-febef700-4be6-11e9-8159-cf32f372406d.png)

相反, 你看v2ex 的页面链接就都是a标签, 所以v2ex seo是可以的
![image](https://user-images.githubusercontent.com/20200267/54736556-a25bd780-4be6-11e9-814a-0048d3b6b376.png)
![image](https://user-images.githubusercontent.com/20200267/54736599-e3ec8280-4be6-11e9-973c-f2e59d43223d.png)

**Comment by OrangeXC** [comment]
这个项目的目的就是不让爬虫去抓过多的东西，因为目前项目跑在 heroku 平台上的免费版，每个月只提供 500 分钟的免费服务时间，我的账号同时跑了 3 个项目在上面，所以尽量避免爬虫抓取消耗的流量

另：此站点仅仅为演示站点，并非对外宣传，如研究代码请在本地打包运行，因为每个月的资源有限，请不要浪费浏览时间，谢谢
