### ISSUE TITLE
跑不起来啊

### ISSUE THREAD

**Issue by 1966767119** [OrangeXC/n2ex#27]
不晓得是网的问题还是依赖问题，总之没跑起来，install没问题，run的时候各种报错，楼主还是看看的好

**Comment by OrangeXC** [comment]
首先感谢反馈，

其次提 issue 的时候

要先说明开发环境（操作系统和node版本）

然后把你的报错信息截图贴出来

这样有利于排查问题，这项目推上来有几个月了，你是第一个提跑不起来

另外线上地址：https://n2ex.herokuapp.com/

跑的就是这个项目，部署服务器也没有任何问题。

**Comment by 1966767119** [comment]
![warning](https://user-images.githubusercontent.com/3285108/32977000-b0b6ec8a-cbe9-11e7-8880-77a68791b086.png)
我原来也跑起来过，用的是windows,现在是mac环境，截图如下
![yy](https://user-images.githubusercontent.com/3285108/32977021-034cd48c-cbea-11e7-926e-f5da964d8612.png)
求大神帮忙看看呢

**Comment by 1966767119** [comment]
sorry,我昨天是直接下载的zip,yarn或者npm install都搞不定，但今晚我clone下来然后npm install，竟然就好了。也可能与墙有关。还是很欣赏这个项目的，我是写后台的开发，以后可以交个朋友

**Comment by OrangeXC** [comment]
@1966767119 

我看到了你前面发的报错截图，说下你遇到的问题。

在你 `npm install` 的时候 `puppeteer` 这个包安装失败了，首先这个项目里面不依赖  `puppeteer`，所以排除了项目的锅。

至于为什么会顺带给你安装这个库还要看你本地的配置

再讲下 `puppeteer` 是个无头浏览器，可以在 node.js 后端操作网站，包括截屏、模拟浏览器事件、操作 DOM 等。

项目地址：https://github.com/GoogleChrome/puppeteer

这个项目最近安装确实不太顺利，在下载时会出现频繁的失败，我也遇到类似问题，可能与VPN有关
，还可能与代码本身有关（我是改了`puppeteer`源码后再安装的）。

下次可以加微信找我：https://orangexc.xyz/about/

链接里有二维码
