### ISSUE TITLE
目前官网最新版 是0.10.6，请问 1.0.0-alpha1 哪里获取的

### ISSUE THREAD

**Issue by jsgr** [OrangeXC/n2ex#5]
作为一个新手，问的问题都很幼稚，但确实有疑问

**Comment by OrangeXC** [comment]
npm安装时可以指定版本号，版本号在github项目目录界面的左上角，有个下拉菜单可以看到所有版本，

**Comment by jsgr** [comment]
看到谢谢，原来是要切换到 tags才可以。我看到怎么绑定组件的数据了，谢谢。上周末玩了两天，文档不全，各种坑。看来还是我太嫩。

**Comment by jsgr** [comment]
请问有打算写一下教程吗？前端服务器渲染可以的话，就不用担心SEO的问题。用vue做好的项目查看源代码就一个div。这也是硬伤啊。

**Comment by OrangeXC** [comment]
我有写这个项目的教程，可以到我主页左侧的博客里看

**Comment by jsgr** [comment]
有看了，目前是更新两篇了。我有给你评论。期待接下来的教程

**Comment by OrangeXC** [comment]
好的，有时间我会继续写相关文章，感谢支持，哈哈~

**Comment by jsgr** [comment]
谢谢，看到一个疑问就是 footer组件有定义，但是未使用，在default.vue里引用了，可是没有渲染。layouts这一块和vue.js的组件引用位置不太一样，我自己先看看。

**Comment by OrangeXC** [comment]
那个组建只是引用了，模版里面没写 tag标签，准备之后写一个好看点的footer

**Comment by jsgr** [comment]
好的，跟着你学nuxt。哈哈
